/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LmdbOptions {
  path: string
  asyncWrites: boolean
}
export declare function initTracingSubscriber(): void
export interface Entry {
  key: string
  value: Buffer
}
export type LMDB = Lmdb
export declare class Lmdb {
  constructor(options: LmdbOptions)
  get(key: string): Promise<Buffer | null | undefined>
  getSync(key: string): Buffer | null
  getManySync(keys: Array<string>): Array<Buffer | undefined | null>
  putMany(entries: Array<Entry>): Promise<void>
  put(key: string, data: Buffer): Promise<void>
  startTransaction(): Promise<void>
  commitTransaction(): Promise<void>
  close(): void
}
