/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LmdbOptions {
  path: string
  asyncWrites: boolean
}
export declare function initTracingSubscriber(): void
export type LMDB = Lmdb
export declare class Lmdb {
  constructor(options: LmdbOptions)
  get(key: string): Promise<Buffer | null | undefined>
  put(key: string, data: Buffer): Promise<void>
  startTransaction(): Promise<void>
  commitTransaction(): Promise<void>
  close(): void
}
